### ISSUE TITLE
[NEW][TABLE] follow

### ISSUE THREAD

**Issue by kjs775** [Studyvelopers/OverTheFlow-db#10]
### TABLE NAME
follow

### TABLE DESCRIPTION
회원 사이의 팔로우 정보를 저장

### TABLE SCHEMA

NAME | TYPE | CONSTRAINTS
-- | -- | --
member_id | VARCHAR(255) | PFK
follow_id |  VARCHAR(255) | PFK

### TABLE REFERENCES
- member

### TASK LISTS
할 일 목록을 작성합니다.
- [x] 기본 DDL 작성
- [ ] 샘플 데이터 추가
- [ ] 테이블 단위 테스트
