### ISSUE TITLE
[NEW][TABLE] comment

### ISSUE THREAD

**Issue by kjs775** [Studyvelopers/OverTheFlow-db#11]
### TABLE NAME
comment

### TABLE DESCRIPTION
곡에 대한 댓글을 작성한 회원과 댓글의 내용에 대한 정보를 저장

### TABLE SCHEMA

NAME | TYPE | CONSTRAINTS
-- | -- | --
conmment_id | VARCHAR(255) | PK
comment_number | INT | NOT NULL
comment_contents | TEXT | NOT NULL
comment_status | INT | NOT NULL
member_id | VARCHAR(255) | NOT NULL
music_id | VARCHAR(255) | NOT NULL

### TABLE REFERENCES
- member
- music

### TASK LISTS
- [x] 기본 DDL 작성
- [x] 샘플 데이터 추가
- [ ] 테이블 단위 테스트

### BRANCH
