### ISSUE TITLE
[NEW][TABLE] member

### ISSUE THREAD

**Issue by kjs775** [Studyvelopers/OverTheFlow-db#9]
### TABLE NAME
member

### TABLE DESCRIPTION
회원의 정보를 저장

### TABLE SCHEMA

NAME | TYPE | CONSTRAINTS
-- | -- | --
member_id | VARCHAR(255) | PK
member_email | VARCHAR(255) | NOT NULL, UNIQUE
member_password | VARCHAR(255) | NOT NULL
member_nickname | VARCHAR(255) | NOT NULL, UNIQUE
member_introduction | TEXT | NOT NULL
member_register_date | DATETIME | NOT NULL
member_type_id | VARCHAR(20) NOT NULL

### TASK LISTS
할 일 목록을 작성합니다.
- [x] 기본 DDL 작성 
- [ ] 샘플 데이터 추가
- [ ] 테이블 단위 테스트
